name: neighborly
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_fonts: ^8.0.2
  lucide_icons: ^0.257.0
  intl: ^0.20.2
  http: ^1.2.0
  shared_preferences: ^2.2.0
  google_generative_ai: ^0.4.7
  image_picker: ^1.2.1
  uuid: ^4.5.3
  geolocator: ^13.0.2
  local_auth: ^2.3.0
  crypto: ^3.0.6
  video_player: ^2.11.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700
